[local_development]
account = "account_locator.region.cloud_provider" # Your Snowflake account
user = "first_name.last_name@domain.com" # Your Snowflake username
password = "my_password" # Your Snowflake password
database = "dbname" # Snowflake database where the streamlit application related objects will be created
schema = "schema" # Snowflake schema where the streamlit application related objects will be created 
stage = "stage" # Snowflake stage where the streamlit application related source code will be uploaded into
role = "role" # Snowflake role with permissions to create objects and upload files in the schema/stage above
client_session_keep_alive = true

[default_service_account]
account = "account_locator.region.cloud_provider" # Your Snowflake account
user = "service_account_username" # Your Snowflake username
password = "service_account_password" # Your Snowflake password
client_session_keep_alive = true

[streamlit_deployment]
database = "dbname" # Snowflake database where the streamlit application related objects will be created
schema = "schema" # Snowflake schema where the streamlit application related objects will be created 
stage = "stage" # Snowflake stage where the streamlit application related source code will be uploaded into
role = "role" # Snowflake role with permissions to create objects and upload files in the schema/stage above